Style/TrivialAccessors:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false
Metrics/AbcSize:
  Max: 30
AllCops:
  Exclude:
    - 'db/schema.rb'
